# Generated by Django 3.1.7 on 2021-03-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_name',
            field=models.CharField(max_length=100),
        ),
    ]
